name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Astro
        run: yarn build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: hormigon-impreso-sevilla # TODO: replace with Deno Deploy project name
          entrypoint: jsr:@std/http/file-server
          root: dist
